"""
if <wyrażenie jest prawdziwe>:
    <rób coś>
    ....
    ....
elif <poprzednie wyrazenie jest falszywe, ale to prawdziwe>:
    <rób coś innego>
    ....
    ....
else: # jesli zadne z powyzszych nie jest prawdziwe
    <rób jeszcze coś innego>
    ....
    ....
    """
